vim.keymap.set("n", "<A-j>", ":m .+1<CR>==", { noremap = true }) -- move line up(n)
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==", { noremap = true }) -- move line down(n)
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv", { noremap = true }) -- move line up(v)
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv", { noremap = true }) -- move line down(v)
vim.keymap.set("n", "<C-d>", "<C-d>zz", { noremap = true })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { noremap = true })
vim.keymap.set("x", "<leader>p", '"_dP', { desc = "[P]aste w/o copy deleted to buffer" })
vim.keymap.set("n", "<leader>y", '"+y', { desc = "[Y]ank to system clipboard buffer" })
vim.keymap.set("v", "<leader>y", '"+y', { desc = "[Y]ank to system clipboard buffer" })
vim.keymap.set("n", "<leader>Y", '"+Y', { desc = "[Y]ank to system clipboard buffer" })
vim.keymap.set("n", "Q", "<nop>", { desc = "[Y]ank to system clipboard buffer" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<leader>H", "<C-w>H", { desc = "Move window to the left" })
vim.keymap.set("n", "<leader>L", "<C-w>L", { desc = "Move window to the right" })
vim.keymap.set("n", "<leader>J", "<C-w>J", { desc = "Move window to the lower" })
vim.keymap.set("n", "<leader>K", "<C-w>K", { desc = "Move window to the upper" })
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("n", "x", '"_x')
vim.keymap.set("v", "x", '"_x')
vim.keymap.set(
	"n",
	"<leader>rw",
	[[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]],
	{ desc = "[R]eplace [W]ord under cursor" }
)
vim.keymap.set("n", "<leader>X", "<cmd>!chmod +x %<CR>", { desc = "Makes file executable" })
vim.keymap.set("n", "<A-Left>", "<C-o>", { desc = "Go to previous position" })
vim.keymap.set("n", "<A-Right>", "<C-i>", { desc = "Go to next position" })
vim.keymap.set("n", "<leader>ww", ":w<CR>", { desc = "[W]rite curren file" })
vim.keymap.set("n", "<leader>wa", ":wa<CR>", { desc = "[W]rite [A]ll files" })
